In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df.sample()

       job_title_short  ...                   job_type_skills
561125    Data Analyst  ...  {'programming': ['python', 'r']}

[1 rows x 17 columns]

In [3]:
df.sample(10)

              job_title_short  ...                                    job_type_skills
266371         Data Scientist  ...  {'cloud': ['azure'], 'libraries': ['hadoop', '...
128073          Data Engineer  ...  {'analyst_tools': ['sas', 'sap'], 'programming...
28420           Data Engineer  ...  {'analyst_tools': ['tableau', 'power bi'], 'cl...
521785  Senior Data Scientist  ...  {'libraries': ['tensorflow', 'pytorch'], 'prog...
513610  Senior Data Scientist  ...  {'analyst_tools': ['tableau', 'looker'], 'clou...
197661           Data Analyst  ...  {'analyst_tools': ['excel'], 'programming': ['...
733509           Data Analyst  ...                         {'programming': ['nosql']}
435706           Data Analyst  ...              {'async': ['jira'], 'other': ['git']}
89682          Data Scientist  ...  {'analyst_tools': ['tableau'], 'programming': ...
372587          Data Engineer  ...  {'os': ['linux', 'redhat', 'centos', 'debian']...

[10 rows x 17 columns]

In [4]:
df_altered = df

median_salary = df_altered['salary_year_avg'].median()
median_salary

np.float64(115000.0)

In [5]:
df['salary_year_avg'] = df_altered['salary_year_avg'].fillna(median_salary)

df_altered.loc[:5 , 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [6]:
df.loc[:5 , 'salary_year_avg']

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64