In [29]:
import pandas as pd

In [30]:
from datasets import load_dataset

In [31]:
dataset = load_dataset('lukebarousse/data_jobs')

df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [32]:
df['job_posted_date_str'] = df['job_posted_date'].apply(lambda time:time.strftime('%Y-%m-%d'))

In [33]:
df['job_posted_date_str']

0         2023-06-16
1         2023-01-14
2         2023-10-10
3         2023-07-04
4         2023-08-07
             ...
785736    2023-03-13
785737    2023-03-12
785738    2023-03-12
785739    2023-03-12
785740    2023-03-13
Name: job_posted_date_str, Length: 785741, dtype: str

In [34]:
import datetime
datetime.datetime.now()

datetime.datetime(2026, 3, 17, 16, 17, 5, 740028)

In [35]:
df['days_since_posted'] = df['job_posted_date'].apply(lambda time: (datetime.datetime.now()-time).days)

In [36]:
df['days_since_posted']

0         1005
1         1158
2          889
3          987
4          953
          ...
785736    1100
785737    1101
785738    1101
785739    1101
785740    1100
Name: days_since_posted, Length: 785741, dtype: int64

In [37]:
df_filtered = df['salary_year_avg'].dropna().copy()

df_filtered = df_filtered.to_frame()  # convert to DataFrame

In [38]:
df_filtered

        salary_year_avg
28             109500.0
77             140000.0
92             120000.0
100            228222.0
109             89000.0
...                 ...
785624         139216.0
785641         150000.0
785648         221875.0
785682         157500.0
785692         157500.0

[22003 rows x 1 columns]

In [39]:
df_filtered['salary_category'] = df_filtered['salary_year_avg'].apply(
    lambda s: 'Low' if s < 60000 else 'Medium' if s < 100000 else 'High'
)

df_filtered[['salary_year_avg', 'salary_category']]

        salary_year_avg salary_category
28             109500.0            High
77             140000.0            High
92             120000.0            High
100            228222.0            High
109             89000.0          Medium
...                 ...             ...
785624         139216.0            High
785641         150000.0            High
785648         221875.0            High
785682         157500.0            High
785692         157500.0            High

[22003 rows x 2 columns]