In [4]:
import pandas as pd

In [5]:
import matplotlib.pyplot as plt
from datasets import load_dataset

In [6]:
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [7]:
modi_df = df.copy()

In [9]:
modi_df.set_index('job_posted_date', inplace=True)

In [10]:
modi_df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_posted_date,,,,,,,,,,,,,,,,
2023-06-16 13:44:15,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
2023-01-14 13:18:07,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2023-10-10 13:14:55,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
2023-07-04 13:01:41,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2023-08-07 14:29:36,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [14]:
modi_df.reset_index(drop=True, inplace=True)

In [15]:
modi_df

,job_posted_date,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,2023-06-16 13:44:15,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,2023-01-14 13:18:07,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,2023-10-10 13:14:55,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,2023-07-04 13:01:41,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,2023-08-07 14:29:36,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,2023-03-13 06:16:16,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,2023-03-12 06:18:18,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,2023-03-12 06:32:36,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,2023-03-12 06:32:15,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,2023-03-13 06:16:31,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [16]:
df_piv_tbl = df.pivot_table(values='salary_year_avg', index='company_name', aggfunc='median')

df_piv_tbl

                                    salary_year_avg
company_name
#twiceasnice Recruiting                65000.000000
/dev/color                            125000.000000
0nward Select                          92500.000000
1 Point System                        137290.484375
1 Point System LLC.                   170000.000000
...                                             ...
zooplus SE                            161750.000000
ztp                                    95000.000000
ЛАНИТ                                 400000.000000
Технологическая компания              280000.000000
​Illinois State Board of Education     62536.000000

[7316 rows x 1 columns]

In [20]:
df_piv_tbl.sort_index(inplace=True, ascending=False)

In [21]:
df_piv_tbl

                                    salary_year_avg
company_name
​Illinois State Board of Education     62536.000000
Технологическая компания              280000.000000
ЛАНИТ                                 400000.000000
ztp                                    95000.000000
zooplus SE                            161750.000000
...                                             ...
1 Point System LLC.                   170000.000000
1 Point System                        137290.484375
0nward Select                          92500.000000
/dev/color                            125000.000000
#twiceasnice Recruiting                65000.000000

[7316 rows x 1 columns]

In [23]:
new_piv_tbl = df.pivot_table(values='salary_year_avg', index='job_title_short', aggfunc='median')
new_piv_tbl

                           salary_year_avg
job_title_short
Business Analyst                   85000.0
Cloud Engineer                     90000.0
Data Analyst                       90000.0
Data Engineer                     125000.0
Data Scientist                    127500.0
Machine Learning Engineer         106415.0
Senior Data Analyst               111175.0
Senior Data Engineer              147500.0
Senior Data Scientist             155500.0
Software Engineer                  99150.0

In [24]:
new_piv_tbl.reset_index(inplace=True)

In [25]:
new_piv_tbl

             job_title_short  salary_year_avg
0           Business Analyst          85000.0
1             Cloud Engineer          90000.0
2               Data Analyst          90000.0
3              Data Engineer         125000.0
4             Data Scientist         127500.0
5  Machine Learning Engineer         106415.0
6        Senior Data Analyst         111175.0
7       Senior Data Engineer         147500.0
8      Senior Data Scientist         155500.0
9          Software Engineer          99150.0

In [27]:
new_piv_tbl.set_index('salary_year_avg', inplace=True)

In [28]:
new_piv_tbl.head(5)

                  job_title_short
salary_year_avg
85000.0          Business Analyst
90000.0            Cloud Engineer
90000.0              Data Analyst
125000.0            Data Engineer
127500.0           Data Scientist